apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rings-v1-canary
  labels:
    service: hello-rings
    version: v1
    branch: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hello-rings
      version: v1
      branch: canary
  template:
    metadata:
      labels:
        service: hello-rings
        version: v1
        branch: canary
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 2000m
              memory: 250Mi
---
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: hello-rings-v1-canary
spec:
  deploy: true
  routing:
    group:
      name: canary
    service: hello-rings
    version: v1
    branch: canary
    ports:
      - port: 80